### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by paulmwatson** [The-Mycelium-Network/the-mycelium-network#4]
`https://discord.gg/6MrjtEmDgr` is now invalid.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/4352/220088986-eae9ea90-3a84-4ed0-8dbe-ce6abe52c5cc.png">

**Comment by schalkneethling** [comment]
> `https://discord.gg/6MrjtEmDgr` is now invalid. <img alt="image" width="540" src="https://user-images.githubusercontent.com/4352/220088986-eae9ea90-3a84-4ed0-8dbe-ce6abe52c5cc.png">

Just fixed it almost a year later :)
